### ISSUE TITLE
Browser - Scrollback Hides Title

### ISSUE THREAD

**Issue by dak** [Connexions/webview#1254]
Scrolling down to make a book title section hide and then scrolling back up on a Mac with elastic scroll causes the title to be shown and then re-hidden.

![image](https://cloud.githubusercontent.com/assets/1371232/11479142/731f360a-975e-11e5-92f5-d1bba6673fc9.png)

**Comment by RoyEJohnson** [comment]
I think this is fixed in latest master (certainly you won't lose the title), but let me know if elastic scroll still does some unwanted hiding. I don't get any, but I might not be doing what you're doing.

**Comment by dak** [comment]
This issue still exists, although now it just hides/shows the whole header.

**Comment by RoyEJohnson** [comment]
This should be ready to close.
